BOT_TOKEN: 
  - MTE1NjQzNzAyMDYyNTg2MjY2Ng.GZ56IQ.QYHqWJwDBW1WijuZlJcHl0ZtDAaQOEgPage8z8
  - MTE1NjQzNzAyMDYyNTg2MjY2Ng.GZ56IQ.QYHqWJwDBW1WijuZlJcHl0ZtDAaQOEgPage8z8
CHANNEL_ID: 
  - 1156857578983264280
  - 1206576848247717898
MODE: custom
REPLY: 
SIMSIMI_LANG: en
DELAY: 10
DEL_AFTER: 
REPOST_LAST_CHAT: 100
